//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public string Region { get; set; }
        public string Person { get; set; }
        public string Item { get; set; }
        public int Units { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Total { get; set; }
        public System.DateTime AddedOn { get; set; }
    }
}
